  prepare_install   &&
  mkdir  -p      /usr/games/mupen64
  cp     -av  *  /usr/games/mupen64
  chmod  a+rw    /usr/games/mupen64
  chmod  a+rw    /usr/games/mupen64/mupen64.ini
  chmod  a+rw    /usr/games/mupen64/save
  chmod  a+rw    /usr/games/mupen64/plugins

  cp -v ${SCRIPT_DIR}/mupen64.run /usr/games/
  chmod a+rx /usr/games/mupen64.run  
